### GET menu

http://localhost:3000/api/menu


### DELETE menu
DELETE http://localhost:3000/api/menu/662854895d626f0ed814ffcf
### POST menu

POST http://localhost:3000/api/menu
Content-Type: application/json

{
  "name": "test name",
  "description": "test description",
  "price": "test price"
}

###get menu
http://localhost:3000/api/menu

###get event
http://localhost:3000/api/event


###get specific event from id
http://localhost:3000/api/event/662848c8173fdd8cf85b68aa
